allprojects {
    group = 'io.baton'
    version = '1.0.0-SNAPSHOT'

    repositories {
        mavenCentral()
        mavenLocal() // for Angela snapshots: cd /work/terracotta/github/angela && mvn install -DskipTests
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
            }
        }
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Test) {
        useJUnitPlatform()
    }
}
